# Generated by Django 3.1 on 2020-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250, null=True)),
                ('latitude', models.FloatField(max_length=12, null=True)),
                ('longitude', models.FloatField(max_length=12, null=True)),
                ('estpop', models.IntegerField(max_length=12, null=True)),
                ('blevel', models.IntegerField(max_length=12, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citymun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdesc', models.CharField(max_length=250, null=True)),
                ('latitude', models.FloatField(max_length=12, null=True)),
                ('longitude', models.FloatField(max_length=12, null=True)),
                ('cmclass', models.CharField(max_length=250, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
