# Generated by Django 3.1.1 on 2020-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0002_auto_20200906_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymun',
            name='cmclass',
            field=models.CharField(choices=[('City', 'City'), ('Municipality', 'Municipality')], max_length=250, null=True),
        ),
    ]
