# Generated by Django 3.1.1 on 2020-10-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0003_citymun_cmclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_id', models.CharField(max_length=250, null=True)),
                ('establishment_name', models.CharField(max_length=250, null=True)),
                ('establishment_type', models.CharField(max_length=250, null=True)),
                ('establishment_barangay', models.CharField(max_length=250, null=True)),
                ('establishment_citymun', models.CharField(max_length=250, null=True)),
                ('establishment_owner_name', models.CharField(max_length=250, null=True)),
                ('establishment_owner_id', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sys_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, null=True)),
                ('user_fname', models.CharField(max_length=250, null=True)),
                ('user_lname', models.CharField(max_length=250, null=True)),
                ('user_barangay_address', models.CharField(max_length=250, null=True)),
                ('user_citymun_address', models.CharField(max_length=250, null=True)),
                ('user_type', models.CharField(max_length=250, null=True)),
                ('user_username', models.CharField(max_length=250, null=True)),
                ('user_password', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=250, null=True)),
                ('visitor_fname', models.CharField(max_length=250, null=True)),
                ('visitor_lname', models.CharField(max_length=250, null=True)),
                ('visitor_barangay_address', models.CharField(max_length=250, null=True)),
                ('visitor_citymun_address', models.CharField(max_length=250, null=True)),
                ('visitor_contact_no', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
