# Generated by Django 3.1.1 on 2020-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0004_establishment_sys_users_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='establishment_type',
        ),
        migrations.AddField(
            model_name='establishment',
            name='user_type',
            field=models.CharField(choices=[('Government', 'Government'), ('Commercial', 'Commercial'), ('Non-profit', 'Non-profit'), ('Educational', 'Educational'), ('Others', 'Others')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sys_users',
            name='user_type',
            field=models.CharField(choices=[('Level 0', 'Level 0'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], max_length=250, null=True),
        ),
    ]
