# Generated by Django 3.1.1 on 2020-10-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0005_auto_20201005_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sys_users',
            new_name='Sys_user',
        ),
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='user_type',
            new_name='establishment_type',
        ),
    ]
