# Generated by Django 3.1.1 on 2020-10-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0008_barangay_citymun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='citymun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covidtrace.citymun'),
        ),
    ]
