# Generated by Django 3.1.1 on 2020-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0009_auto_20201005_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='citymun',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_email',
            field=models.EmailField(default=None, max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
    ]
