# Generated by Django 3.1.1 on 2020-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0010_auto_20201005_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_email',
            field=models.EmailField(max_length=255, null=True, verbose_name='email'),
        ),
    ]
