# Generated by Django 3.1.1 on 2020-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtrace', '0011_auto_20201005_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_email',
        ),
    ]
